### ISSUE TITLE
16 (2x8) pin board to board mezzanine connector

### ISSUE THREAD

**Issue by wwortel** [bazjo/radiosonde_hardware#14]
Vaisala RS41-SGP
not an issue, but I think I found the manufacturer of the miniature board to board connector, 0.5 mm pitch 2 rows 8 pins.
https://www.kinghelm.net/connector-connector/56111.html

**Comment by nubcore** [comment]
The link referenced returns a 20 pin connector, rather than the expect 16 pin configuration.

There are some close matches from Molex, but nothing that looks identical, filtered DigiKey search...

https://www.digikey.com/en/products/filter/arrays-edge-type-mezzanine-board-to-board/308?s=N4IgjCBcoGwJxVAYygMwIYBsDOBTANCAPZQDaIALAAxwDMdIAuoQA4AuUIAymwE4CWAOwDmIAL6EAHJMQgUkDDgLEy4KrQDsYKk1YdI3PkNESQkhNDloseQiUjkArACYwz3SHaceAkeNPuDiAARkTovAAmAARsRFGh4dFIRIKCuEixvExiQA
